/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jYjg55ntSKv
 */
import { Button } from "@/components/ui/button"

export function NewsCard() {
  return (
    <div className="bg-[#1A1A1A] text-white py-16 px-4">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="flex flex-col items-center bg-[#111] p-6 rounded-tl-lg rounded-br-lg overflow-visible relative">
          <div className="relative z-10 transform -translate-y-1/2">
            <img
              alt="Esport event"
              className="w-full h-auto"
              height="300"
              src="/pxb-media-logo.png"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="absolute inset-0 bg-[#00abf5] opacity-50" />
          <div className="z-10 p-4">
            <h2 className="text-xl font-bold">Big scale esport events and projects, but easier.</h2>
            <Button className="mt-4" variant="outline">
              Read more
            </Button>
          </div>
        </div>
        <div className="flex flex-col items-center p-6 rounded-tl-lg rounded-br-lg overflow-visible relative">
          <div className="relative z-10 transform -translate-y-1/2">
            <img
              alt="Gaming keyboard"
              className="w-full h-auto"
              height="300"
              src= "/pxb-media-logo.png"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="absolute inset-0 bg-[#00abf5] opacity-50" />
          <div className="z-10 p-4">
            <h2 className="text-xl font-bold">Big scale esport events and projects, but easier.</h2>
            <Button className="mt-4" variant="outline">
              Read more
            </Button>
          </div>
        </div>
        <div className="flex flex-col items-center bg-[#111] p-6 rounded-tl-lg rounded-br-lg overflow-visible relative">
          <div className="relative z-10 transform -translate-y-1/2">
            <img
              alt="Gaming mouse"
              className="w-full h-auto"
              height="300"
              src= "/pxb-media-logo.png"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width="300"
            />
          </div>
          <div className="absolute inset-0 bg-[#00abf5] opacity-50" />
          <div className="z-10 p-4">
            <h2 className="text-xl font-bold">Big scale esport events and projects, but easier.</h2>
            <Button className="mt-4" variant="outline">
              Read more
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
